version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/nestjs-app
      - JWT_SECRET=e65f9f3bbfd58f3db72cbcb42996d7d1e1a57469a9d38e557a6ed1d08863e1ff
      - JWT_REFRESH_SECRET=e65f9f3bbfd58f3db72cbcb42996d7d1e1a57469a9d38e557a6ed1d08863e1jj
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: